In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy as sp
import os
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

selected_columns = [
    'Player', 'Pos','Squad','Comp','MP','Min',
    'Gls','Ast','G+A','xG','xAG', 'npxG' ,
    'Sh','SoT','SoT%','KP', 'Succ%',
    'SCA','GCA'
]

df = pd.read_csv(
    r"D:\Salah_Performance\Dataset\players_data_light-2024_2025.csv", 
    usecols=selected_columns
)

In [3]:
df

,Player,Pos,Squad,Comp,MP,Min,Gls,Ast,G+A,xG,npxG,xAG,Sh,SoT,SoT%,KP,SCA,GCA,Succ%
0,Max Aarons,DF,Bournemouth,eng Premier League,3,86,0,0,0,0.0,0.0,0.0,0,0,NaN,0,2,0,0.0
1,Max Aarons,"DF,MF",Valencia,es La Liga,4,120,0,0,0,0.0,0.0,0.0,0,0,NaN,1,1,0,25.0
2,Rodrigo Abajas,DF,Valencia,es La Liga,1,65,0,0,0,0.1,0.1,0.0,1,0,0.0,0,0,0,100.0
3,James Abankwah,"DF,MF",Udinese,it Serie A,6,88,0,0,0,0.1,0.1,0.0,1,0,0.0,0,1,0,NaN
4,Keyliane Abdallah,FW,Marseille,fr Ligue 1,1,3,0,0,0,0.0,0.0,0.0,0,0,NaN,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,Edhy Zuliani,DF,Toulouse,fr Ligue 1,1,9,0,0,0,0.0,0.0,0.0,0,0,NaN,0,0,0,NaN
2850,Szymon Żurkowski,MF,Empoli,it Serie A,5,106,0,0,0,0.1,0.1,0.0,2,0,0.0,0,1,0,50.0
2851,Martin Ødegaard,MF,Arsenal,eng Premier League,30,2325,3,8,11,4.8,4.0,5.4,48,15,31.3,63,124,18,42.4
2852,Milan Đurić,FW,Monza,it Serie A,18,1270,4,1,5,2.9,2.9,1.1,23,10,43.5,5,7,1,66.7
2853,Milan Đurić,FW,Parma,it Serie A,9,268,1,0,1,0.3,0.3,0.0,5,1,20.0,0,5,1,100.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2854 entries, 0 to 2853
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  2854 non-null   object
 1   Pos     2854 non-null   object
 2   Squad   2854 non-null   object
 3   Comp    2854 non-null   object
 4   MP      2854 non-null   int64
 5   Min     2854 non-null   int64
 6   Gls     2854 non-null   int64
 7   Ast     2854 non-null   int64
 8   G+A     2854 non-null   int64
 9   xG      2854 non-null   float64
 10  npxG    2854 non-null   float64
 11  xAG     2854 non-null   float64
 12  Sh      2854 non-null   int64
 13  SoT     2854 non-null   int64
 14  SoT%    2335 non-null   float64
 15  KP      2854 non-null   int64
 16  SCA     2854 non-null   int64
 17  GCA     2854 non-null   int64
 18  Succ%   2411 non-null   float64
dtypes: float64(5), int64(10), object(4)
memory usage: 423.8+ KB

<h1> Cleaning </h1>

In [6]:
df.rename(columns={
    'G+A': 'GA',
    'SoT%': 'SoT_pct',
    'Succ%': 'Succ_pct'
}, inplace=True)

In [7]:
df['SoT_pct'] = df['SoT_pct'].fillna(0)
df['Succ_pct'] = df['Succ_pct'].fillna(0)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df = df[df['Min'] >= 300]

In [10]:
df['Goals_per90'] = round((df['Gls'] / df['Min']) * 90, 2)
df['Assists_per90'] = round((df['Ast'] / df['Min']) * 90, 2)
df['xG_per90'] = round((df['xG'] / df['Min']) * 90, 2)

In [11]:
df['Finishing'] = round(df['Gls'] - df['xG'], 2)

In [12]:
df['Shot_Accuracy'] = round((df['SoT'] / df['Sh']) * 100, 2)

In [13]:
df.replace([np.inf, -np.inf], 0, inplace=True)

<h1> Analysis </h1>

In [15]:
salah = df[df['Player'] == 'Mohamed Salah']
salah

,Player,Pos,Squad,Comp,MP,Min,Gls,Ast,GA,xG,...,SoT_pct,KP,SCA,GCA,Succ_pct,Goals_per90,Assists_per90,xG_per90,Finishing,Shot_Accuracy
2304,Mohamed Salah,FW,Liverpool,eng Premier League,38,3371,29,18,47,25.2,...,41.3,88,169,27,42.3,0.77,0.48,0.67,3.8,41.32

Gls , Ast , GA , MP

In [17]:
Salah_Goals = df[df['Player'] == 'Mohamed Salah']['Gls']
Salah_Goals

2304    29
Name: Gls, dtype: int64

In [18]:
Salah_Assists = df[df['Player'] == 'Mohamed Salah']['Ast']
Salah_Assists

2304    18
Name: Ast, dtype: int64

In [19]:
Salah_GA = df[df['Player'] == 'Mohamed Salah']['GA']
Salah_GA

2304    47
Name: GA, dtype: int64

In [20]:
Salah_Matches = df[df['Player'] == 'Mohamed Salah']['MP']
Salah_Matches

2304    38
Name: MP, dtype: int64

In [26]:
salah = df[df['Player'] == 'Mohamed Salah']

on_target = salah['SoT'].values[0]

off_target = (
    salah['Sh'].values[0]
    - salah['SoT'].values[0]
)

print("On Target:", on_target)
print("Off Target:", off_target)

On Target: 50
Off Target: 71

In [28]:
goals = salah['Gls'].values[0]
xg = salah['xG'].values[0]
print(goals ,',' , xg)

29 , 25.2

Salah >> Overperforming , Good finishing

In [30]:
Assists = salah['Ast'].values[0]
Chances = salah['GCA'].values[0]
Key_pass = salah['KP'].values[0]
print(Assists ,',' , Chances , ',' , Key_pass)

18 , 27 , 88

Liverpool attackers underperform the quality of chances created by Salah.

In [32]:
Top_Scorers = df.sort_values(
    by='GA',
    ascending=False
).head(10)
Top_Scorers

,Player,Pos,Squad,Comp,MP,Min,Gls,Ast,GA,xG,...,SoT_pct,KP,SCA,GCA,Succ_pct,Goals_per90,Assists_per90,xG_per90,Finishing,Shot_Accuracy
2304,Mohamed Salah,FW,Liverpool,eng Premier League,38,3371,29,18,47,25.2,...,41.3,88,169,27,42.3,0.77,0.48,0.67,3.8,41.32
1317,Harry Kane,FW,Bayern Munich,de Bundesliga,31,2381,26,9,35,20.3,...,42.9,35,89,21,43.4,0.98,0.34,0.77,5.7,42.86
1691,Kylian Mbappé,FW,Real Madrid,es La Liga,34,2907,31,3,34,25.9,...,49.3,51,133,15,44.4,0.96,0.09,0.80,5.1,49.34
2201,Mateo Retegui,FW,Atalanta,it Serie A,36,2383,25,8,33,18.9,...,32.3,38,76,14,40.0,0.94,0.30,0.71,6.1,32.32
1483,Robert Lewandowski,FW,Barcelona,es La Liga,34,2667,27,2,29,27.1,...,40.5,19,50,3,57.1,0.91,0.07,0.91,-0.1,40.54
1219,Alexander Isak,FW,Newcastle Utd,eng Premier League,34,2756,23,6,29,20.3,...,43.2,41,92,14,46.2,0.75,0.20,0.66,2.7,43.16
1693,Bryan Mbeumo,FW,Brentford,eng Premier League,38,3414,20,7,27,12.3,...,43.0,70,144,20,46.8,0.53,0.18,0.32,7.7,43.04
1960,Michael Olise,"FW,MF",Bayern Munich,de Bundesliga,34,2334,12,15,27,9.7,...,41.9,90,169,25,47.7,0.46,0.58,0.37,2.3,41.86
2177,Raphinha,"FW,MF",Barcelona,es La Liga,36,2839,18,9,27,19.2,...,35.7,91,163,22,50.5,0.57,0.29,0.61,-1.2,35.71
697,Ousmane Dembélé,FW,Paris S-G,fr Ligue 1,29,1730,21,6,27,16.6,...,51.0,63,110,15,44.2,1.09,0.31,0.86,4.4,51.04

- Comparing Salah to the best wingers (contributions)
- Comparing Salah to the best playmakers (key passes)

In [35]:
df.to_csv(r'D:\Salah_Performance\Dataset_After_Transform.csv', index=False)